name: Pengeruk Data Otomatis Tiap Jam

on:
  schedule:
    - cron: '0 * * * *' # Format rahasia artinya: Jalankan otomatis setiap menit ke-0 di setiap jam
  workflow_dispatch: # Fitur bonus agar Anda bisa menyalakan robot ini secara manual kapan saja

jobs:
  pengeruk:
    runs-on: ubuntu-latest
    steps:
    - name: Membuka Folder Proyek
      uses: actions/checkout@v4

    - name: Menyiapkan Mesin Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Menginstal Library yang Dibutuhkan
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Menyalakan Mesin Pengeruk Berita
      run: python engine.py

    - name: Mengirim Hasil JSON Terbaru ke Website
      run: |
        git config --global user.name "Robot-Otomatis-NPCC"
        git config --global user.email "robot@npcc.com"
        git add live_data.json
        git commit -m "Pembaruan otomatis data intelijen oleh sistem" || exit 0
        git push
